version: '3'

services:

  gems:
    image: busybox:latest
    container_name: project5_gems
    command: /bin/echo
    volumes:
      - /project5-gems

  postgres:
    image: postgres:9
    container_name: project5_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
    expose:
      - 5432
    volumes:
      - project5-postgres:/var/lib/postgresql/data

  redis:
    image: redis:4
    container_name: project5_redis
    expose:
      - 6379
    volumes:
      - project5-redis:/var/lib/redis/data

  backend:
    container_name: project5_backend
    build: .
    env_file:
      - .env
    command: ["rails s -p 3000 -b 0.0.0.0"]
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    volumes:
      - .:/project5
    depends_on:
      - gems
      - postgres
      - redis

  sidekiq:
    container_name: project5_sidekiq
    build: .
    command: ["sidekiq -C config/sidekiq.yml"]
    env_file:
      - .env
    depends_on:
      - backend

volumes:

  project5-gems:
  project5-postgres:
  project5-redis:
