version: '3'

services:

  project5_box:
    image: busybox
    container_name: project5_box
    # restart: always
    volumes:
      - /project5-box

  project5_postgres:
    image: postgres:9
    container_name: project5_postgres
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
    ports:
      - '5432:5432'
    volumes:
      - project5-postgres:/var/lib/postgresql/data

  project5_redis:
    image: redis:4
    container_name: project5_redis
    # restart: always
    ports:
      - '6379:6379'
    volumes:
      - project5-redis:/var/lib/redis/data

  project5_backend:
    container_name: project5_backend
    build: .
    env_file:
      - .env
    command: bash -c "./start.sh"
    # restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/project5
    depends_on:
      - project5_box
      - project5_postgres
      - project5_redis

  project5_sidekiq:
    container_name: project5_sidekiq
    build: .
    command: sidekiq -C config/sidekiq.yml
    # restart: always
    env_file:
      - .env
    depends_on:
      - project5_backend

volumes:

  project5-box:
  project5-postgres:
  project5-redis:
