version: '2'

services:

  postgres:
    image: postgres:9.6.2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - project5-postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.0.7
    ports:
      - '6379:6379'
    volumes:
      - project5-redis:/var/lib/redis/data

  project5:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/project5
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    env_file:
      - .project5.env

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    links:
      - postgres
      - redis
    volumes:
      - .:/project5
    env_file:
      - .project5.env

volumes:

  project5-postgres:
  project5-redis:
