defaults: &defaults
  adapter: postgresql
  encoding: unicode
  database: <%= "#{ENV['DB_NAME']}_#{ENV['RAILS_ENV']}" %>
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  # host: 172.18.0.1

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
