development: &default
  adapter: postgresql
  encoding: unicode
  database: project5_development
  pool: 5
  username: zheka
  password:
  # host: db

# test:
#   <<: *default
#   database: project5_test
