development:
  adapter: postgresql
  encoding: unicode
  database: my_project_development
  pool: 5
  username: zheka
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: my_project_test
  pool: 5
  username: zheka
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: my_project_production
  pool: 5
  password:
